defaults:
  - _self_
  - model_kwargs: stereo-simulation-normalize

inner_loops: 5
inner_loss_fn: MSELoss
inner_optim_fn: Adam
inner_optim_fn_kwargs:
  lr: 0.01
  weight_decay: 0.02
outer_optim_fn_kwargs:
  lr: 0.05
global_l1_lambda: 0.015

clip_A: true
adj_kwargs:
  init_edge_weights: trunc_normal

apply_hier_prox: false

log_A_every_k_epochs: 10