defaults:
  - _self_
  - model_kwargs: stereo-simulation

inner_loops: 5
inner_loss_fn: MSELoss
inner_optim_fn: Adam
inner_optim_fn_kwargs:
  lr: 0.01
  weight_decay: 0.02
outer_optim_fn_kwargs:
  lr: 0.05
smoothness_lambda: 1.0

clip_A: false
adj_kwargs:
  init_edge_weights: glorot

apply_hier_prox: true
hier_prox_kwargs:
  min_n_nonzero: 10
  soft_lambda: 0.01
  M: 1.0
  path_multiplier: 0.02
  warm_epochs: 30
  run_every_n: 1

log_A_every_k_epochs: 10
save_A_seq: false
