defaults:
  - _self_
  - dataset: ???
  - module_conf: ???

module: ???
max_epochs: 1000
log_every_n_steps: 1

ckpt: null  # determine important TFs from hier-prox ckpt
dataset_ckpt: null  # useful for simulation
sources_ckpt: null  # text file of python lists

warm_init: false   # use correlations as init

seed: 1