defaults:
  - _self_
  - dataset: simulated-data-max
  - module_conf: ???

module: ???
max_epochs: 500
log_every_n_steps: 1

ckpt: null  # determine important TFs from hier-prox ckpt
dataset_ckpt: 'data/simulation/max-simulation.pkl'
sources_ckpt: null  # text file of python lists

seed: 1